import { chromium, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true, args: ['--no-sandbox'] });
await mkdir('test-results', { recursive: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1024 }, deviceScaleFactor: 1, hasTouch: true });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto('http://localhost:3000');
await page.waitForFunction(() => { const image = document.getElementById('horse-portrait'); return image?.complete && image.naturalWidth > 0; });
assert.equal(await page.locator('#home-view canvas').count(), 0);
await page.evaluate(() => document.fonts.ready);
assert.equal(await page.evaluate(() => document.fonts.check('16px NanumSquareRound')), true);
console.log('Font: NanumSquareRound loaded');
await page.screenshot({ path: 'test-results/home-desktop.png', fullPage: true });
console.log('Desktop:', await page.title(), 'overflow:', await page.evaluate(() => document.documentElement.scrollWidth > innerWidth));
assert.equal(await page.locator('#name-feedback').textContent(), '');
assert.equal(await page.getByRole('button', { name: '혼자 달리기', exact: true }).isEnabled(), false);
await page.getByRole('button', { name: '확인', exact: true }).click();
assert.equal(await page.locator('#name-feedback').evaluate(el => getComputedStyle(el).backgroundColor), 'rgba(0, 0, 0, 0)');
assert.equal(await page.locator('#name-feedback').evaluate(el => getComputedStyle(el).borderWidth), '0px');
console.log('Empty validation:', await page.locator('#name-feedback').textContent());
await page.getByRole('textbox', { name: '말 이름', exact: true }).fill('삼성전자');
assert.equal(await page.locator('#name-feedback').textContent(), '');
await page.getByRole('button', { name: '확인', exact: true }).click();
await expect(page.locator('#name-feedback')).toContainText('회사', { timeout: 30000 });
console.log('Brand validation:', await page.locator('#name-feedback').textContent());
await page.getByRole('textbox', { name: '말 이름', exact: true }).fill('트리플나인');
assert.equal(await page.locator('#name-feedback').textContent(), '');
await page.getByRole('button', { name: '확인', exact: true }).click();
await expect(page.locator('#name-feedback')).toContainText('기존 말 이름', { timeout: 30000 });
assert.equal(await page.getByRole('button', { name: '혼자 달리기', exact: true }).isEnabled(), false);
console.log('Existing horse validation:', await page.locator('#name-feedback').textContent());
await page.screenshot({ path: 'test-results/name-existing-horse.png' });
// Editing during an outstanding lookup must invalidate its eventual approval.
let releaseLookup, markLookupStarted;
const lookupStarted = new Promise(resolve => { markLookupStarted = resolve; });
const lookupReleased = new Promise(resolve => { releaseLookup = resolve; });
await page.route('**/api/validate-name', async route => {
  markLookupStarted();
  await lookupReleased;
  await route.fulfill({ json: { ok: true, message: '사용 가능한 이름입니다.' } }).catch(() => {});
});
await page.getByRole('textbox', { name: '말 이름', exact: true }).fill('바람을따라');
await page.getByRole('button', { name: '확인', exact: true }).click();
await lookupStarted;
await page.getByRole('textbox', { name: '말 이름', exact: true }).fill('이름바꿨다');
releaseLookup();
await page.unrouteAll({ behavior: 'wait' });
assert.equal(await page.getByRole('button', { name: '혼자 달리기', exact: true }).isEnabled(), false);
assert.equal(await page.locator('#preview-name').textContent(), '말 이름');
await page.getByRole('button', { name: '말 이름 무작위 추천', exact: true }).click();
await page.getByRole('button', { name: '확인', exact: true }).click();
await expect(page.locator('#preview-name')).toHaveText('바람을따라', { timeout: 30000 });
await expect(page.locator('#name-feedback')).toHaveText('사용 가능한 이름입니다.');
// Editing a confirmed name clears its approval without showing warnings.
await page.getByRole('textbox', { name: '말 이름', exact: true }).fill('바람 따라');
assert.equal(await page.locator('#name-feedback').textContent(), '');
assert.equal(await page.getByRole('button', { name: '혼자 달리기', exact: true }).isEnabled(), false);
await page.getByRole('textbox', { name: '말 이름', exact: true }).press('Enter');
assert.match(await page.locator('#name-feedback').textContent(), /띄어쓰기/);
await page.getByRole('textbox', { name: '말 이름', exact: true }).fill('바람을따라');
await page.getByRole('button', { name: '확인', exact: true }).click();
await page.getByRole('button', { name: '혼자 달리기', exact: true }).click();
await page.getByRole('dialog').waitFor();
await page.screenshot({ path: 'test-results/lobby-desktop.png' });
await page.getByRole('button', { name: '키보드로 체험', exact: false }).click();
await page.getByRole('button', { name: '경주 시작하기', exact: false }).click();
await page.getByText('달려!', { exact: true }).waitFor({ timeout: 7000 });
await page.getByText('달려!', { exact: true }).waitFor({ state: 'hidden' });
await page.screenshot({ path: 'test-results/race-desktop.png' });
for (let i = 0; i < 8; i++) { await page.keyboard.press('Space'); await new Promise(resolve => setTimeout(resolve, 160)); }
console.log('Accelerated speed:', await page.locator('#speed-value').textContent());
assert.equal(await page.locator('#speed-value').textContent(), '72');
const finishDeadline = Date.now() + 22000;
while (!(await page.locator('#result-dialog').isVisible()) && Date.now() < finishDeadline) {
  await page.keyboard.press('Space');
  await new Promise(resolve => setTimeout(resolve, 170));
}
await page.locator('#result-dialog').waitFor({ state: 'visible' });
console.log('Finish:', await page.locator('#result-title').textContent(), await page.locator('#result-time').textContent());
assert.ok(parseFloat(await page.locator('#result-time').textContent()) >= 15);
await page.screenshot({ path: 'test-results/result-desktop.png' });
await page.waitForFunction(() => !document.getElementById('replay').disabled, { timeout: 25000 });
await page.getByRole('button', { name: '다시 경주', exact: false }).click();
await page.locator('#lobby-dialog').waitFor({ state: 'visible' });
console.log('Rematch:', await page.locator('#mic-title').textContent());
assert.equal(await page.locator('#mic-title').textContent(), '마이크를 연결해주세요');
await page.getByRole('button', { name: '대기실 나가기', exact: true }).click();
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: 'test-results/home-mobile.png', fullPage: true });
console.log('Mobile overflow:', await page.evaluate(() => document.documentElement.scrollWidth > innerWidth));
await page.getByRole('button', { name: '친구와 달리기', exact: true }).click();
await page.locator('#invite-link').waitFor();
const invite = await page.locator('#invite-link').inputValue();
const friend = await browser.newPage({ viewport: { width: 390, height: 844 } });
await friend.goto(invite);
// Opening the link alone reserves nothing, so there is no distinct horse yet.
await expect(friend.locator('#invite-banner')).toContainText('1/8명 참가');
await friend.getByRole('textbox', { name: '말 이름', exact: true }).fill('바람을따라');
await friend.getByRole('button', { name: '완료', exact: true }).click();
await expect(friend.locator('#name-feedback')).toContainText('같은 이름');
assert.equal(await friend.locator('#lobby-dialog').evaluate(dialog => dialog.open), false);
await friend.getByRole('textbox', { name: '말 이름', exact: true }).fill('천둥발굽');
await friend.getByRole('button', { name: '완료', exact: true }).click();
await page.getByText('2/8명 참가', { exact: true }).waitFor();
assert.equal(new Set(await page.locator('#lobby-players .player-avatar img').evaluateAll(images => images.map(image => image.src))).size, 2);
assert.notEqual(await page.locator('#horse-portrait').getAttribute('src'), await friend.locator('#horse-portrait').getAttribute('src'));
console.log('Friends room:', await page.locator('#lobby-description').textContent());
await page.screenshot({ path: 'test-results/friends-mobile.png' });
console.log('Page errors:', errors);
await browser.close();
if (errors.length) process.exitCode = 1;
